# Generated by Django 2.1 on 2018-08-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180717_2150'),
        ('web', '0008_auto_20180717_1910'),
    ]

    operations = [
    ]
